In [1]:
import torch


### Everything is multi-dimension array of floating-point

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
a[2] = -1
a

tensor([ 1.,  1., -1.])

### Python's list to Tensor

In [6]:
points = torch.tensor([1, 2, 3, 4, 5, 6, 7.0])
points

tensor([1., 2., 3., 4., 5., 6., 7.])

In [7]:
points = torch.tensor([[1, 2, 3], [4.0, 5.0, 6.0]])
points

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
points.shape

torch.Size([2, 3])

### Named tensors

In [9]:
img_t = torch.randn(3, 5, 5)  # shape: [channels, rows, columns]
weights = torch.tensor([0.2, 0.3, 0.4])

In [10]:
batch_t = torch.randn(2, 3, 5, 5)  # shape [batch_size, channels, rows, columns]

In [13]:
# mean: Returns the mean value of all elements in the input tensor at dim

img_gray_naive = img_t.mean(-3)  # counting from the end
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [24]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weight = (img_t * unsqueezed_weights)
batch_weight = (batch_t * unsqueezed_weights)

img_gray_weight = img_weight.sum(-3)
batch_gray_weight = batch_weight.sum(-3)

batch_weight.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [41]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
print(f"img named: {img_named.shape} {img_named.names}")

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')


/Volumes/MacDATA/VSCodeWorkSpace/Python/PyTorch-DL-fundamental/venv/lib/python3.9/site-packages/torch/_tensor.py:780: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1156.)
  return super(Tensor, self).refine_names(names)


### Tensor element type

* `torch.float32` or `torch.float`: 32-bit floating point
* `torch.float64` or `torch.double`: 64-bit floating point
* ...
* `torch.int8`: signed 8-bit integers
* ...
* `torch.int64` or `torch.long`: signed 64-bit integers
* `torch.boolean`: boolean

### Create tensor with specified `dtype`

In [42]:
double_points = torch.tensor([1, 2, 3], dtype=torch.double)
short_points = torch.ones(10, 2, dtype=torch.short)

double_points, short_points

(tensor([1., 2., 3.], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [43]:
# rand: random from 0 -> 1
torch.rand(3).double()

tensor([0.4451, 0.8098, 0.3434], dtype=torch.float64)

### Tensor API

In [44]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)  # a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [45]:
# transpose without copying

points = torch.randn(3, 2, dtype=torch.double)
points_t = points.t()

points.shape, points_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [49]:
points_3d = torch.randn(2, 3, 4)
points_3d_t = points_3d.transpose(1, 2)

points_3d.shape, points_3d_t.shape

(torch.Size([2, 3, 4]), torch.Size([2, 4, 3]))